---
- name: apt update
  apt: update_cache=true

- name: apt-get install common packages
  apt: pkg={{item}}
  with_items:
    - build-essential
    - ruby-dev
    - git
    - ntp

- name: create root directory
  file: path={{ root_path }}
        state=directory
        owner={{ app_user }}
        group={{ app_user }}
        mode=0777
  tags: checkout
