defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5
  # reaping_frequency: 10

development:
  <<: *defaults
  database: fran_dev

test: &test
  <<: *defaults
  database: fran_test

production:
  <<: *defaults
  database: fran_production