# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6785435bbaeebdcf9875ca0f57d342339f461ebf22d2ee0efe2ce168df1fb278dec9068e4ce5de1978b44f9c859a826d0076bbc42fb99617e9eb95b01f6d689

test:
  secret_key_base: 3bd24f13d58551c6f00cb908d44683848f77444779127ef066e8e0c1f553f8ff578965e89eeec16923102bfae6dba98612c10edff3c8e49b629102123b0fa1b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
