---
sidekiq:
  config_dir: config
  workers:
    - service_name: sidekiq_1
      user: '{{ web_user }}'
      pid_file: tmp/pids/sidekiq_1.pid
      log_file: log/sidekiq_1.log
      reliable_index:
      config_file: sidekiq_1.yml
      concurrency: 10
      dynamic: true
      verbose: true
      require:
      timeout:
      queues:
        - name: default
          priority: