---
- name: add apt repository
  apt_repository: repo='ppa:nginx/stable'

- name: apt update
  apt: update_cache=true

- name: install nginx
  apt: name=nginx state=present
  tags: nginx

- name: remove default nginx configuration
  file: name=/etc/nginx/sites-enabled/default state=absent
  tags: nginx

- name: copy nginx configuration
  template: src=nginx.conf.j2 dest={{ nginx_dir }}/nginx.conf
  notify: restart nginx
  tags: nginx

- name: create monit nginx conf
  template: src=etc/monit/conf.d/nginx.conf.j2 dest=/etc/monit/conf.d/nginx.conf
  notify: reload monit
  tags: nginx
