---
- hosts: web
  sudo: yes
  vars:
    unicorn:
      server_name: cfsmr.spiridonov.pro
    env: production
    deployment_parent_dir: /opt
    root_path: "{{ deployment_parent_dir }}/fran"
    releases_path: "{{ root_path }}/releases"
    current_release_link: '{{ root_path + "/current" }}'
    current_application_link: '{{ current_release_link }}'
    shared_path: "{{ root_path}}/shared"
    db_username: postgres
    db_password: postgres
    db_host: localhost
    db_name: fran_production
    db_port: 5432
    shared_database_yml: '{{ shared_path + "/config/database.yml" }}'
    sys_user: root
    web_user: www-data
    app_user: "{{ ansible_ssh_user }}"
  roles:
    - common
    - monit
    - postgres
    - nginx
    - brightbox-ruby
    - rails_app
    - logrotate
    - unicorn
